/*
 * Unique id for every element is generated by simply appending the position index with parentid.
 * The parentId is the unique id of parent component ( it can be either a form or a field )
 * The id of top most form component is auto generated using Math.random.
 * Since id is a function of parentId and element index, we will get consistent , but unique id for each component
 */
function vfjsHelperGenerateField(field, parentId) {
  if (!field) {
    return false;
  }

  const { children = [] } = field;

  return {
    ...field,
    id: parentId,
    children: children.map((child, i) =>
      this.vfjsHelperGenerateField(child, `${parentId}-${i}`),
    ),
  };
}

export default vfjsHelperGenerateField;
