export const VFS_EVENT_CHANGE = 'VFS_EVENT_CHANGE';
export const VFS_EVENT_MODEL_UPDATED = 'VFS_EVENT_MODEL_UPDATED';
export const VFS_EXTERNAL_EVENT_CHANGE = 'change';
export const VFS_EXTERNAL_EVENT_VALIDATED = 'validated';
