import {
  VFJS_EXTERNAL_EVENT_CHANGE,
  VFJS_EXTERNAL_EVENT_STATE_CHANGE,
  VFJS_EXTERNAL_EVENT_VALIDATED,
  VFJS_EXTERNAL_MODEL_PROP,
} from '../constants';

const emits = [
  VFJS_EXTERNAL_EVENT_CHANGE,
  VFJS_EXTERNAL_EVENT_STATE_CHANGE,
  VFJS_EXTERNAL_EVENT_VALIDATED,
  VFJS_EXTERNAL_MODEL_PROP,
];

export default emits;
